services:
  mysql:
    image: mysql:8
    container_name: rdam-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rdam
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  rdam-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rdam-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

  pluspagos:
    build:
      context: ./pasarela-campus-2026/pasarela-campus-2026/pluspagos-mock-simple
      dockerfile: Dockerfile
    container_name: pluspagos-mock
    ports:
      - "3010:3000"

volumes:
  mysql_data:
